---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: SSH Hardening
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        #- {regex: "^[#]{0,1}Port", line: "Port 3223"}
        - {regex: "^[#]{0,1}AllowAgentForwarding", line: "AllowAgentForwarding no"}
        - {regex: "^[#]{0,1}AllowTcpForwarding", line: "AllowTcpForwarding no"}
        - {regex: "^[#]{0,1}ClientAliveCountMax", line: "ClientAliveCountMax 2"}
        - {regex: "^[#]{0,1}LogLevel", line: "LogLevel VERBOSE"}
        - {regex: "^[#]{0,1}MaxAuthTries", line: "MaxAuthTries 3"}
        - {regex: "^[#]{0,1}MaxSessions", line: "MaxSessions 2"}
        - {regex: "^[#]{0,1}TCPKeepAlive", line: "TCPKeepAlive no"}
        - {regex: "^[#]{0,1}X11Forwarding", line: "X11Forwarding no"}
        - {regex: "^[#]{0,1}PermitRootLogin", line: "PermitRootLogin no"}
        - {regex: "^[#]{0,1}PasswordAuthentication", line: "PasswordAuthentication no"}
        - {regex: "^[#]{0,1}PermitEmptyPasswords", line: "PermitEmptyPasswords no"}
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
    - name: disable protocols dcp, dccp_diag, rds, sctp, tipc
      copy:
        dest: /etc/modprobe.d/CIS.conf
        content: |
          install dccp /bin/true
          install dccp_diag /bin/true
          install rds /bin/true
          install sctp /bin/true
          install tipc /bin/true
          install usb-storage /bin/true
    - name: install packages
      package:
        name:
          - apt-show-versions
          - debsums
        state: latest
    - name: banner
      copy:
        dest: "/etc/{{ item }}"
        content: |
          #################################################################
          #                   _    _           _   _                      #
          #                  / \  | | ___ _ __| |_| |                     #
          #                 / _ \ | |/ _ \ '__| __| |                     #
          #                / ___ \| |  __/ |  | |_|_|                     #
          #               /_/   \_\_|\___|_|   \__(_)                     #
          #                                                               #
          #  You are entering into a secured area! Your IP, Login Time,   #
          #   Username has been noted and has been sent to the server     #
          #                       administrator!                          #
          #   This service is restricted to authorized users only. All    #
          #            activities on this system are logged.              #
          #  Unauthorized access will be fully investigated and reported  #
          #        to the appropriate law enforcement agencies.           #
          #################################################################
      loop:
        - issue
        - issue.net
    - name: Password aging
      lineinfile:
        path: /etc/login.defs
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - {regex: "^PASS_MAX_DAYS", line: "PASS_MAX_DAYS 90"}
        - {regex: "^PASS_MIN_DAYS", line: "PASS_MIN_DAYS 1"}
        - {regex: "^PASS_WARN_AGE", line: "PASS_WARN_AGE 14"}

          
